spring:
  application:
    name: eureka-server

server:
  port: 8302

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
      
zuul:
 prefix: /api
 routes: 
  book-services:
    path: /book-services/**
    url: http://localhost:8300
  order-services:
    path: /order-services/**
    url: http://localhost:8301